### ISSUE TITLE
updeep does not keep result of `object instanceof MyClass`

### ISSUE THREAD

**Issue by ZeHiro** [substantial/updeep#66] opened 2016-09-11 21:34 UTC
When updating the property of an object with updeep, the 'type' of objects created with classes is not kept. This then raises errors with React, when checking props with React prop validator.

**Comment by aaronjensen** [comment] 2016-09-12 01:04
Hi @ZeHiro, thanks for reporting.

Do you have a failing test case? I wasn't aware of the `__proto__` property. From my brief reading it seems like it's not something that is meant to be [used nowadays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto). Though maybe its' the actual backing for `getPrototyepOf`

Any way, updeep was primarily designed to work w/ regular objects. I'm guessing that `__proto__` is not enumerable and so therefore would not come over when we create a new object. I'm not sure if it's worth adding a special case for `__proto__ or not. You're welcome to submit a pull request and we can see what would be necessary. Thanks!

**Comment by ZeHiro** [comment] 2016-09-12 05:54
@aaronjensen 

In fact, what I observed is: 
- The store is an array of MyClass, ie for each element of the store, ` element instanceof MyClass` returns true.
- When modifying one of the elements, the test `modified_element instanceof MyClass` return false.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FOperators%2Finstanceof
(it seams instanceof uses the __proto__ property)
Concerning the react Test failing, we use prop validation using React.PropTypes.instanceOf(MyClass)

**Comment by aaronjensen** [comment] 2016-09-14 20:04
Thanks @ZeHiro for the explanation.

At this point I'd say this is as designed/expected. Updeep is intended to work on basic data structures (objects, arrays) and not class instances. One could easily argue that using updeep to mutate class instance properties is an anti-pattern given the fact that classes are generally meant to encapsulate their state.

I'm going to close this as wontfix for now. 

I don't know exactly how you're using classes in the classes or why you're wanting to use updeep to mutate them, but one suggestion may be to have class functions that use updeep to update class properties and return a new instance of the class like: `new MyClass(u({...}, this))`.

**Closed by aaronjensen** 2016-09-14 20:04 UTC
Labels: wontfix

**Comment by ZeHiro** [comment] 2016-09-14 21:39
Thanks for you're answer. That's whzt i thought after rethinking of that issue.
